version: "3"
services:
  app:
    container_name: app
    build: ./
    restart: always
    ports:
    - "8080:3000"
    volumes:
        - .:/app
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
        - ./myDb:/data/myDb
    ports:
    - "27017:27017"